In [52]:
import tensorflow as tf
tf.__version__

'2.0.0'

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation
import os
import io
import pandas as pd
import requests
import numpy as np
from sklearn import metrics

In [54]:

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])


In [55]:
cars = df['name']

In [56]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0    18.0          8         307.0       130.0    3504          12.0    70   
1    15.0          8         350.0       165.0    3693          11.5    70   
2    18.0          8         318.0       150.0    3436          11.0    70   
3    16.0          8         304.0       150.0    3433          12.0    70   
4    17.0          8         302.0       140.0    3449          10.5    70   
..    ...        ...           ...         ...     ...           ...   ...   
393  27.0          4         140.0        86.0    2790          15.6    82   
394  44.0          4          97.0        52.0    2130          24.6    82   
395  32.0          4         135.0        84.0    2295          11.6    82   
396  28.0          4         120.0        79.0    2625          18.6    82   
397  31.0          4         119.0        82.0    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
393       1            ford mustang gl  
394       2                  vw pickup  
395       1              dodge rampage  
396       1                ford ranger  
397       1                 chevy s-10  

[398 rows x 9 columns]

In [57]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

In [58]:
x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
y = df['mpg'].values


In [59]:
model = Sequential()
model.add(Dense(25,input_dim = x.shape[1],activation = 'relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(1))
model.compile(loss = 'mean_squared_error',optimizer = 'adam')
model.fit(x,y,verbose=2,epochs=100)

Train on 398 samples
Epoch 1/100
398/398 - 1s - loss: 88245.3524
Epoch 2/100
398/398 - 0s - loss: 3779.9544
Epoch 3/100
398/398 - 0s - loss: 5341.5062
Epoch 4/100
398/398 - 0s - loss: 1194.0058
Epoch 5/100
398/398 - 0s - loss: 1075.8312
Epoch 6/100
398/398 - 0s - loss: 778.2955
Epoch 7/100
398/398 - 0s - loss: 754.5645
Epoch 8/100
398/398 - 0s - loss: 728.8955
Epoch 9/100
398/398 - 0s - loss: 704.4383
Epoch 10/100
398/398 - 0s - loss: 694.3634
Epoch 11/100
398/398 - 0s - loss: 677.3557
Epoch 12/100
398/398 - 0s - loss: 664.5052
Epoch 13/100
398/398 - 0s - loss: 653.1256
Epoch 14/100
398/398 - 0s - loss: 651.1431
Epoch 15/100
398/398 - 0s - loss: 625.1733
Epoch 16/100
398/398 - 0s - loss: 625.1875
Epoch 17/100
398/398 - 0s - loss: 615.6080
Epoch 18/100
398/398 - 0s - loss: 601.2188
Epoch 19/100
398/398 - 0s - loss: 588.2079
Epoch 20/100
398/398 - 0s - loss: 587.3311
Epoch 21/100
398/398 - 0s - loss: 571.7856
Epoch 22/100
398/398 - 0s - loss: 561.1430
Epoch 23/100
398/398 - 0s - loss: 55

In [60]:
pred = model.predict(x)
pred.shape

(398, 1)

In [61]:
print(pred)

[[16.817785 ]
 [14.687193 ]
 [14.761641 ]
 [15.691092 ]
 [15.921476 ]
 [14.097876 ]
 [11.881094 ]
 [12.33219  ]
 [12.435278 ]
 [12.22724  ]
 [11.462133 ]
 [13.889624 ]
 [12.735807 ]
 [ 2.107878 ]
 [20.719458 ]
 [18.926123 ]
 [18.346998 ]
 [17.413    ]
 [19.802908 ]
 [19.742243 ]
 [23.315405 ]
 [20.77056  ]
 [21.03716  ]
 [17.224401 ]
 [17.51103  ]
 [20.061285 ]
 [21.70365  ]
 [20.463797 ]
 [25.69956  ]
 [19.863619 ]
 [17.348211 ]
 [19.429037 ]
 [18.516874 ]
 [14.9382305]
 [21.921217 ]
 [19.983854 ]
 [20.214582 ]
 [20.58341  ]
 [18.8478   ]
 [17.784796 ]
 [19.172308 ]
 [20.393423 ]
 [22.253775 ]
 [20.263037 ]
 [23.118902 ]
 [15.899641 ]
 [19.958761 ]
 [19.501112 ]
 [18.717001 ]
 [17.710348 ]
 [17.885393 ]
 [21.443693 ]
 [19.494944 ]
 [20.356089 ]
 [18.684397 ]
 [18.922472 ]
 [19.391523 ]
 [20.235998 ]
 [19.233164 ]
 [23.52381  ]
 [19.48107  ]
 [18.418325 ]
 [19.409826 ]
 [17.35639  ]
 [20.875189 ]
 [18.920172 ]
 [17.53568  ]
 [16.346106 ]
 [21.894873 ]
 [21.357153 ]
 [17.213293 ]
 [22.0

In [62]:
score = np.sqrt(metrics.mean_squared_error(pred,y))
score

8.424670032045606

In [63]:
for i in range(10):
    print(f"{i+1}. Car name: {cars[i]}, MPG: {y[i]}, predicted MPG: {pred[i]}")

1. Car name: chevrolet chevelle malibu, MPG: 18.0, predicted MPG: [16.817785]
2. Car name: buick skylark 320, MPG: 15.0, predicted MPG: [14.687193]
3. Car name: plymouth satellite, MPG: 18.0, predicted MPG: [14.761641]
4. Car name: amc rebel sst, MPG: 16.0, predicted MPG: [15.691092]
5. Car name: ford torino, MPG: 17.0, predicted MPG: [15.921476]
6. Car name: ford galaxie 500, MPG: 15.0, predicted MPG: [14.097876]
7. Car name: chevrolet impala, MPG: 14.0, predicted MPG: [11.881094]
8. Car name: plymouth fury iii, MPG: 14.0, predicted MPG: [12.33219]
9. Car name: pontiac catalina, MPG: 14.0, predicted MPG: [12.435278]
10. Car name: amc ambassador dpl, MPG: 15.0, predicted MPG: [12.22724]


In [64]:
#the above was a regression and below will be classification

In [65]:
from tensorflow.keras.callbacks import EarlyStopping

In [66]:

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

In [67]:
df

sepal_l  sepal_w  petal_l  petal_w         species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
3        4.6      3.1      1.5      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      2.5      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[150 rows x 5 columns]

In [68]:
x = df[['sepal_l','sepal_w','petal_l','petal_w']].values
dummies = pd.get_dummies(df['species'])
species = dummies.columns
y = dummies.values

model = Sequential()
model.add(Dense(50,input_dim = x.shape[1],activation = 'relu'))
model.add(Dense(25,activation = 'relu'))
model.add(Dense(y.shape[1],activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy',optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Train on 150 samples
Epoch 1/100
150/150 - 1s - loss: 1.2400
Epoch 2/100
150/150 - 0s - loss: 1.1358
Epoch 3/100
150/150 - 0s - loss: 1.0836
Epoch 4/100
150/150 - 0s - loss: 1.0440
Epoch 5/100
150/150 - 0s - loss: 0.9992
Epoch 6/100
150/150 - 0s - loss: 0.9532
Epoch 7/100
150/150 - 0s - loss: 0.9099
Epoch 8/100
150/150 - 0s - loss: 0.8715
Epoch 9/100
150/150 - 0s - loss: 0.8294
Epoch 10/100
150/150 - 0s - loss: 0.7898
Epoch 11/100
150/150 - 0s - loss: 0.7512
Epoch 12/100
150/150 - 0s - loss: 0.7146
Epoch 13/100
150/150 - 0s - loss: 0.6814
Epoch 14/100
150/150 - 0s - loss: 0.6495
Epoch 15/100
150/150 - 0s - loss: 0.6206
Epoch 16/100
150/150 - 0s - loss: 0.5942
Epoch 17/100
150/150 - 0s - loss: 0.5688
Epoch 18/100
150/150 - 0s - loss: 0.5476
Epoch 19/100
150/150 - 0s - loss: 0.5225
Epoch 20/100
150/150 - 0s - loss: 0.5022
Epoch 21/100
150/150 - 0s - loss: 0.4842
Epoch 22/100
150/150 - 0s - loss: 0.4645
Epoch 23/100
150/150 - 0s - loss: 0.4469
Epoch 24/100
150/150 - 0s - loss: 0.4316
Epoc

In [69]:
print(species)

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')


In [70]:
pred = model.predict(x)
print(f"Shape  {pred.shape}")

Shape  (150, 3)


In [71]:
print(pred)

[[9.98707414e-01 1.29246467e-03 1.70310742e-07]
 [9.97136712e-01 2.86253076e-03 7.64453716e-07]
 [9.97856319e-01 2.14308477e-03 5.43536828e-07]
 [9.96241450e-01 3.75732384e-03 1.22673646e-06]
 [9.98734891e-01 1.26495655e-03 1.66804412e-07]
 [9.98461246e-01 1.53868669e-03 1.24162938e-07]
 [9.97531891e-01 2.46746489e-03 6.04863942e-07]
 [9.98167872e-01 1.83176575e-03 2.99476540e-07]
 [9.95289564e-01 4.70820954e-03 2.21352002e-06]
 [9.97508407e-01 2.49103014e-03 5.78910601e-07]
 [9.99062598e-01 9.37276112e-04 7.76533469e-08]
 [9.97428477e-01 2.57105008e-03 5.22854066e-07]
 [9.97465849e-01 2.53340253e-03 6.94092364e-07]
 [9.97541189e-01 2.45779869e-03 1.02722447e-06]
 [9.99663472e-01 3.36586148e-04 1.38154039e-08]
 [9.99531984e-01 4.68079292e-04 1.64422236e-08]
 [9.99227285e-01 7.72716769e-04 5.66586777e-08]
 [9.98518884e-01 1.48091523e-03 2.04555008e-07]
 [9.98858333e-01 1.14158122e-03 7.30818144e-08]
 [9.98762488e-01 1.23739440e-03 1.30230418e-07]
 [9.97911155e-01 2.08855886e-03 2.548814

In [72]:
print(y[0:10])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [73]:
prediction = np.argmax(pred,axis=1)
expected = np.argmax(y,axis=1)
print(f"Predictions: {prediction}")
print(f"Expected: {expected}")

Predictions: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Expected: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [74]:
print(species[prediction[1:10]])

Index(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'],
      dtype='object')


In [75]:
from sklearn.metrics import accuracy_score


correct = accuracy_score(expected,prediction)
print(f"Accuracy: {correct}")

Accuracy: 0.98


In [76]:
sample_flower = np.array( [[1.0,1.0,1.0,1.0]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred)
print(f"Predict that {sample_flower} is: {species[pred]}")



[[0.11807707 0.41003647 0.47188643]]
Predict that [[1. 1. 1. 1.]] is: Iris-virginica
